# Generated by Django 3.2.4 on 2021-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, null=True, verbose_name='firstname')),
                ('lastname', models.TextField(blank=True, null=True, verbose_name='lastname')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('dob', models.DateField(null=True, verbose_name='dob')),
                ('gender', models.TextField(blank=True, null=True, verbose_name='gender')),
                ('nationality', models.TextField(blank=True, null=True, verbose_name='nationality')),
            ],
            options={
                'db_table': 'user_management',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
